### ISSUE TITLE
建议修改下文档中配置文件示例

### ISSUE THREAD

**Issue by 912988434** [tkestack/image-transfer#1]
文档中给出的配置文件应该是缩进丢失了，运行会出现如下报错
```
2020-12-30 14:26:30.908 error   configs/config.go:141   decode config file ./rule.yaml error: unmarshal config error: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `registr...` into map[string]string
```
建议修改为如下：

镜像鉴权配置文件
```
grant-test.tencentcloudcr.com:
  username: xxx
  password: xxx
grant-test2.tencentcloudcr.com:
  username: xxx
  password: xxx
registry.cn-hangzhou.aliyuncs.com:
  username: xxx
  password: xxx
ccr.ccs.tencentyun.com:
  username: xxx
  password: xxx
registry.hub.docker.com:
  username: xxx
  password: xxx
test-jingwei.tencentcloudcr.com:
  username: xxx
  password: xxx
```
镜像迁移仓库配置文件
```
"sichenzhao/private-test:xx": "grant-test2.tencentcloudcr.com/xxx/xxx"
```
