### ISSUE TITLE
我的harbor全是http开头的.求如何改代码, http也能运行

### ISSUE THREAD

**Issue by Got99** [tkestack/image-transfer#2]

**Comment by fishingfly** [comment]
在security.yaml里配置insecure为true就行了吧。
```
registry.xxx:
  username: admin
  password: xxx
  insecure: true
```
